services:
  frankenphp:
    build:
      context: .
      dockerfile: docker/FrankenPHP/Dockerfile
    depends_on:
      database:
        condition: service_healthy
      mailhog:
        condition: service_started
    environment:
      APP_ENV: ${APP_ENV:-dev}
      APP_SECRET: ${APP_SECRET:-change-me}
      DATABASE_URL: postgresql://app:app@database:5432/openfoodfacts?serverVersion=16&charset=utf8
      MAILER_DSN: smtp://mailhog:1025
      SERVER_NAME: ${SERVER_NAME:-:80}
    volumes:
      - ./:/app
      - ./docker/FrankenPHP/conf.d/${SYMFONY_INI_FILE:-symfony.dev.ini}:/usr/local/etc/php/conf.d/symfony.app.ini:ro
    ports:
      - "80:80"

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-openfoodfacts}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-openfoodfacts}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  mailhog:
    image: mailhog/mailhog
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
